/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lifefit.Presentacion;

/**
 *
 * @author elver
 */
public class DashBoardPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashBoardPrincipal.class.getName());

    /**
     * Creates new form DashBoardPrincipal
     */
    public DashBoardPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    VistaInicio pantallaInicio = new VistaInicio();
pantallaInicio.setSize(650, 560);
pantallaInicio.setLocation(0, 0);

jPanel4.removeAll();
jPanel4.add(pantallaInicio, java.awt.BorderLayout.CENTER);
jPanel4.revalidate();
jPanel4.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Inicio = new java.awt.Button();
        Alimentacion = new java.awt.Button();
        Rutina = new java.awt.Button();
        Cerrar_Sesion = new java.awt.Button();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        Inicio.setLabel("Inicio");
        Inicio.addActionListener(this::InicioActionPerformed);

        Alimentacion.setLabel("Alimentacion");
        Alimentacion.addActionListener(this::AlimentacionActionPerformed);

        Rutina.setLabel("Rutinas");
        Rutina.addActionListener(this::RutinaActionPerformed);

        Cerrar_Sesion.setLabel("Cerrar Sesion");
        Cerrar_Sesion.addActionListener(this::Cerrar_SesionActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alimentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Rutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Cerrar_Sesion, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Rutina, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Cerrar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 560));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 650, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
VistaInicio pantallaInicio = new VistaInicio();
pantallaInicio.setSize(650, 560);
pantallaInicio.setLocation(0, 0);

jPanel4.removeAll();
jPanel4.add(pantallaInicio, java.awt.BorderLayout.CENTER);
jPanel4.revalidate();
jPanel4.repaint();    }//GEN-LAST:event_InicioActionPerformed

    private void AlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentacionActionPerformed
VistaAlimentacion pantallaAlimentacion = new VistaAlimentacion();
pantallaAlimentacion.setSize(650, 560);
pantallaAlimentacion.setLocation(0, 0);
jPanel4.removeAll();
jPanel4.add(pantallaAlimentacion, java.awt.BorderLayout.CENTER);
jPanel4.revalidate();
jPanel4.repaint();    }//GEN-LAST:event_AlimentacionActionPerformed

    private void RutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutinaActionPerformed
     VistaRutinas pantallaRutinas = new VistaRutinas();
pantallaRutinas.setSize(650, 560);
pantallaRutinas.setLocation(0, 0);

jPanel4.removeAll();
jPanel4.add(pantallaRutinas, java.awt.BorderLayout.CENTER);
jPanel4.revalidate();
jPanel4.repaint();
    }//GEN-LAST:event_RutinaActionPerformed

    private void Cerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_SesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cerrar_SesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashBoardPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Alimentacion;
    private java.awt.Button Cerrar_Sesion;
    private java.awt.Button Inicio;
    private java.awt.Button Rutina;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
